---
# vars file for config
wallpaper:
- key: /org/gnome/desktop/background/picture-uri #Wallpaper
  value: "'file:///home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers/root.png'"

config_files:
- src: .bash_aliases
  dest: /home/{{ ansible_env.SUDO_USER }}
- src: aliases.zsh
  dest: /home/{{ ansible_env.SUDO_USER }}/.oh-my-zsh/custom
- src: .vimrc
  dest: /home/{{ ansible_env.SUDO_USER }}
- src: .tmux.conf
  dest: /home/{{ ansible_env.SUDO_USER }}
- src: .digrc
  dest: /home/{{ ansible_env.SUDO_USER }}

url_fonts:
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf