---
- name: Copy Custom Config Files to Home Directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ config_files }}"

- name: Create Wallpaper Directory 
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755
    state: directory

- name: Create Fonts Directory
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/.fonts"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755
    state: directory

- name: Copy Pictures to ~/Imagens/Wallpapers
  copy:
    src: root.png
    dest: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers/root.png"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644

- name: Download MesloLGS Fonts
  get_url:
    url: "{{ item.url }}"
    dest: "/home/{{ ansible_env.SUDO_USER }}/.fonts/{{ item.name }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ url_fonts }}"

- name: Set Default Wallpaper
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"
  loop: "{{ wallpaper }}"

- name: Load MesloLGS Fonts
  shell: >
    fc-cache -f "/home/{{ ansible_env.SUDO_USER }}/.fonts"

- name: Set vim as Default Editor
  lineinfile:
    path: /etc/environment
    line: "EDITOR=vim"
    state: present